name: homelab
services:
  ajbrowser:
    build: .
    ports:
      - "3100:3000"
    volumes:
      - ./prisma:/app/prisma:rw
      - /home/basse/backups/ajbrowser:/app/public/archives:ro
    command: npm run start
    networks:
      - npm

networks:
  npm:
    external: true
