name: homelab
services:
  ajbrowser:
    build: .
    ports:
      - "3100:3000"
    volumes:
      - ./prisma/store.db:/app/prisma/store.db
    command: npm run start
    networks:
      - npm

networks:
  npm:
    external: true